version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  simulator:
    image: ${DOCKER_REGISTRY-}simulator
    build:
      context: .
      dockerfile: Simulator/Dockerfile
  denomination-routine:
    image: ${DOCKER_REGISTRY-}denominationroutine
    build:
      context: .
      dockerfile: DenominationRoutine/Dockerfile
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql-server
    hostname: sql-server
    environment:
      MSSQL_SA_PASSWORD: 'RiaMoney!123'
      ACCEPT_EULA: 'Y'
      MSSQL_TCP_PORT: '1433'
    restart: unless-stopped
    ports:
      - "1433:1433"